//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _2021_AdventOfCode.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_2021_AdventOfCode.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected advent day has at least 1 activity. Please select a number with the range 1 - .
        /// </summary>
        internal static string DayActivitiesMessage {
            get {
                return ResourceManager.GetString("DayActivitiesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To begin, select a day # within the range of 1 - .
        /// </summary>
        internal static string GettingStartedMessage {
            get {
                return ResourceManager.GetString("GettingStartedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately an invalid Activity day was entered..
        /// </summary>
        internal static string InvalidActivityDay {
            get {
                return ResourceManager.GetString("InvalidActivityDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately an invalid Advent day was entered..
        /// </summary>
        internal static string InvalidAdventDay {
            get {
                return ResourceManager.GetString("InvalidAdventDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some strange reason the activity you selected could not be found..
        /// </summary>
        internal static string LostActivity {
            get {
                return ResourceManager.GetString("LostActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For some strange reason the advent day could not be found..
        /// </summary>
        internal static string LostAdventDay {
            get {
                return ResourceManager.GetString("LostAdventDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unfortunately no Advent days have been registered as yet. Please check back tomorrow..
        /// </summary>
        internal static string MissingAdventDays {
            get {
                return ResourceManager.GetString("MissingAdventDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press &apos;R&apos; to retry, or &apos;X&apos; to exit..
        /// </summary>
        internal static string RetryMessage {
            get {
                return ResourceManager.GetString("RetryMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merry Christmas for 2021! Welcome to the Advent of Code..
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME TO ACTIVITY .
        /// </summary>
        internal static string WelcomeToActivityMessage {
            get {
                return ResourceManager.GetString("WelcomeToActivityMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WELCOME TO DAY .
        /// </summary>
        internal static string WelcomeToDayMessage {
            get {
                return ResourceManager.GetString("WelcomeToDayMessage", resourceCulture);
            }
        }
    }
}
